### ISSUE TITLE
Feature TODO list

### ISSUE THREAD

**Issue by rootofmylife** [rootofmylife/base-template#7]
**Is your feature request related to a problem? Please describe.**

- [ ] add nginx file for deployment
- [ ] add coding style (flake8, prettier,..)
- [ ] configure CI/CD for GitHub actions
- [ ] create new branch that supports Vuetify
- [ ] create new branch that supports TailwindCSS
- [ ] Support SEO
- [ ] Clean docs

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
